# Generated by Django 5.2.11 on 2026-02-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_is_staff_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=11, null=True, verbose_name='Teléfono')),
                ('pais', models.CharField(choices=[('ES', 'ESPAÑA'), ('FR', 'FRANCIA'), ('EN', 'INGLATERRA')], default='ES', help_text='(Obligatorio)', max_length=3, verbose_name='País')),
                ('edad', models.PositiveIntegerField(choices=[(18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65)], default=18, help_text='(Obligatorio)', verbose_name='Edad')),
            ],
            options={
                'verbose_name': '3. Dato',
                'verbose_name_plural': '3. Datos',
                'db_table': 'information_personal',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
