# Generated by Django 5.2.11 on 2026-02-20 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(unique=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=3)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('genre', models.CharField(choices=[('sci_fi', 'Sci-Fi'), ('romance', 'Romance'), ('drama', 'Drama')], max_length=50)),
                ('image', models.ImageField(upload_to='peliculas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
            ],
            options={
                'verbose_name_plural': 'Peliculas',
                'db_table': 'peliculas',
                'ordering': ['rating', 'year'],
            },
        ),
    ]
